//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainView
    {
        public int Trip_number { get; set; }
        public string plane { get; set; }
        public string town_from { get; set; }
        public string town_to { get; set; }
        public System.DateTime time_out { get; set; }
        public System.DateTime time_in { get; set; }
        public string Passenger_name { get; set; }
        public System.DateTime Flight_date { get; set; }
        public string Seat { get; set; }
        public Company company { get; set; }
    }
}
