//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengersInTripView
    {
        public int trip_no { get; set; }
        public string place { get; set; }
        public System.DateTime date { get; set; }
        public string name { get; set; }
        public int ID_psg { get; set; }
    }
}
